import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Layout from '@/components/Layout';
import Header from '@/components/Header';
import CatSlider from '@/components/slider/catSlideer/CatSlider';
import HeadTitle from '@/components/HeadTitle';

export default function Home(data: any) {
  return (
    <>
      <Head>
        <title>kq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Layout>
        <Header />

        {/* do you knows */}
        <div className="bg-gray-100">
          <section className="lg:container mx-auto px-2 lg:py-24 lg:px-24 pt-20">
            <div>
              <HeadTitle eng="Do you know" th="รู้หรือไม่" />
            </div>

            {/* knowlage container */}
            <div className="flex flex-col gap-20 lg:gap-64 mt-10">
              {/* knowlage item */}
              <div className="flex flex-col-reverse flex-col md:flex-row-reverse gap-10">
                <div className="flex-1">
                  <article>
                    <h2 className="text-lg lg:text-2xl  px-3 text-sky-900">
                      การแตะจมูกเป็นการทักทายอย่างหนึ่ง
                    </h2>
                    <p className="mt-5 lg:leading-[4rem] leading-[2rem] indent-6 text-sm ml-3 lg:text-lg">
                      เวลาที่เห็นแมวเอาจมูกมาแตะกันไม่ใช่เรื่องผิดปกติอะไร
                      เพราะอาการดังกล่าวเป็นแค่การทักทายแบบแมวทั่วไป
                      แต่อย่างไรพวกมันจะทักทายด้วยวิธีดังกล่าวกับแมวที่คุ้นเคยเท่านั้น
                      ในขณะเดียวกันก็เป็นวิธีที่การสื่อสารเพื่อเช็กข้อมูลว่า
                      อีกฝ่ายเป็นอย่างไรบ้างนั่นเอง
                    </p>
                  </article>
                </div>
                <div className="flex-1">
                  <div className="rounded-full w-full lg:w-64  mx-auto  overflow-hidden">
                    <img
                      src="/cats/USAshorthair/05.png "
                      className="w-full"
                      alt=""
                    />
                  </div>
                </div>
              </div>

              {/* knowlage item */}
              <div className="flex flex-col-reverse md:flex-row gap-10">
                <div className="flex-1">
                  <article>
                    <h2 className="text-lg lg:text-2xl px-3 text-sky-900">
                      การแตะจมูกเป็นการทักทายอย่างหนึ่ง
                    </h2>
                    <p className="mt-5 leading-[2rem] indent-6 text-sm ml-3 lg:leading-[4rem] lg:text-lg">
                      เวลาที่เห็นแมวเอาจมูกมาแตะกันไม่ใช่เรื่องผิดปกติอะไร
                      เพราะอาการดังกล่าวเป็นแค่การทักทายแบบแมวทั่วไป
                      แต่อย่างไรพวกมันจะทักทายด้วยวิธีดังกล่าวกับแมวที่คุ้นเคยเท่านั้น
                      ในขณะเดียวกันก็เป็นวิธีที่การสื่อสารเพื่อเช็กข้อมูลว่า
                      อีกฝ่ายเป็นอย่างไรบ้างนั่นเอง
                    </p>
                  </article>
                </div>
                <div className="flex-1">
                  <div className="rounded-full w-full lg:w-64  mx-auto  overflow-hidden">
                    <img
                      src="/cats/USAshorthair/05.png "
                      className="w-full"
                      alt=""
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>

        {/* top 10 cats slider */}
        <div className="mt-64">
          <CatSlider />
        </div>
      </Layout>
    </>
  );
}
